### ISSUE TITLE
🤡Add enemies to rooms

### ISSUE THREAD

**Issue by peschkaj** [legitbiz/SealsOfFate#4]
- [x] Create enemies
- [x] Enemies can move
- [ ] Enemies can be generated and placed by the Level or Room generator

**Comment by peschkaj** [comment]
I see two penguins and they can move.

Is there anything outstanding on this?

**Comment by connorkuehl** [comment]
No, but perhaps this should remain open until we have some semblance of actual level generation open to avoid a redundant issue down the line.

**Comment by peschkaj** [comment]
Putting this on the backlog for now since it's waiting on #42 and #7
