### ISSUE TITLE
Combat/AI

### ISSUE THREAD

**Issue by peschkaj** [legitbiz/SealsOfFate#5]
- Create a combat system
- Turn based
- Array of actors (enemies & player)
- Melee

Outstanding Features:
- [ ] Collision detection
- [ ] Modify HP held in `GameManager` (the blubber stat)
- [ ] Player deals damage to enemies

**Comment by Zonr0** [comment]
I am working on the AI piece of this

**Comment by peschkaj** [comment]
Would you have any problem with splitting this into two components so we can close out part of this and allow people to make progress in other areas of either combat or advancing AI?

**Comment by Zonr0** [comment]
Go for it!

**Comment by peschkaj** [comment]
This is replaced by issues #55 and #56
