### ISSUE TITLE
🐱‍👤Enemy AI

### ISSUE THREAD

**Issue by peschkaj** [legitbiz/SealsOfFate#55]

**Comment by peschkaj** [comment]
Where are we on this? Did this get committed and never tracked?

**Comment by Zonr0** [comment]
I'm waiting on combat to get a bit more defined before I start really working on hooking up the attacks to it. Once we have that, we'll have a simple placeholder AI good enough for MVP, but as more systems come online, development will continue on this. (eg. pathfinding, attack selection, etc.)

**Comment by peschkaj** [comment]
Eh, you could always hardcode attacks for now and then we can perform surgery when we merge #56

**Comment by Zonr0** [comment]
Since we have our basic AI implemented. I'm closing this issue. Further enhancements should have their own issues created.
