### ISSUE TITLE
⚔CombatData revisions

### ISSUE THREAD

**Issue by peschkaj** [legitbiz/SealsOfFate#73]
- [x] Modify `IAttackable` to do something reasonable (like provide an attack and defend)
- [x] `CombatData` has a `List<DefenseInfo>` (line 14) that should probably be `List<DefenseEffect>`. 
- [x] Damage calculation in `ComputeDamage` should be changed to apply `List<DefenseEffect>` in addition to applying the mitigations from the `DefenseInfo` property.
- [x] Add the container object to Player and Enemy
- [x] Move all combat scripts to a new folder

I move the last item into issue #75 - Create a `DefenseEffect` class that mirrors `AttackEffect`(on hold until `AttackEffect` is better defined).

**Comment by Zonr0** [comment]
* Move all combat scripts into a new combat folder
* Add a CombatStats class that both Player and Enemy will hold
* Modify AttackInfo or create a new class to encapsulate an entire attack in a beast's or player's repertoire

**Comment by Zonr0** [comment]
* `CombatInfo` should move all the damage information into a new `AttackEffect` named `EffectDamage`.

**Comment by peschkaj** [comment]
> 

> CombatInfo should move all the damage information into a new AttackEffect named EffectDamage.
--

That's what `AttackInfo` is for.

**Comment by peschkaj** [comment]
> Modify `AttackInfo` or create a new class to encapsulate an entire attack in a beast's or player's repertoire

What did you have in mind with this change? Was it adding effects and tags to the `AttackInfo`? Or did you see something else?

(Bonus points for spelling repertoire correctly)

**Comment by peschkaj** [comment]
Further refining tags and effects seems in order. I'm thinking that an effect's `Apply` should take both the attacker's data and the defender's data - it might double damage or half armor or move the attacker or something. Whereas a tag is only applied to the defender's combat data.

**Comment by peschkaj** [comment]
This has been finished (barring the rethinking of tags and effects). Since that has a separate issue open, I'm closing this one.

Feel free to re-open, though, if I'm mistaken.
