### ISSUE TITLE
🐞Moving on top of food powerups causes the editor to hang

### ISSUE THREAD

**Issue by Zonr0** [legitbiz/SealsOfFate#80]
As issue title. The game and editor hangs when attempting to move on top of a food powerup.

Reproduction:
1. Move around the level until you find a fish icon
1. Move onto the fish icon
1. Weep as you are forced to force close the editor using the task manager.

**Comment by Zonr0** [comment]
There also seem to be uncaught exceptions in pathfinding occasionally when near the food. Assuming this is a pathfinding bug until proven otherwise.

**Comment by peschkaj** [comment]
Can confirm. In game console doesn't show anything alarming, but Unity itself becomes unresponsive. CPU utilization stays low.

**Comment by TsebMagi** [comment]
Just confirmed it was when the seals moved onto a fish. could it be that the path finding never resolves because it can't find seal?

**Comment by TsebMagi** [comment]
Penguins actually avoid the fish currently, not sure if that helps, but I just played ring around the fishy with a lovely trio of penguins and they treated it like a pilar

**Comment by Zonr0** [comment]
I had a showerthought™ this morning. Writing it down for future reference. This hang could be caused by the pathfinder looping back on itself. When generating edges, it doesn't check to see if the edge it's about to create was used to get to the tile/node that the pathfinder is currently on.

**Comment by connorkuehl** [comment]
> Penguins actually avoid the fish currently, not sure if that helps, but I just played ring around the fishy with a lovely trio of penguins and they treated it like a pilar

Fishies are their god. They treat it with gentle reverence.
